# Project information
site_name: make-sense
site_url: https://skalskip.github.io/make-sense
site_author: Piotr Skalski
site_description: free to use online tool for labelling photos

# Repository
repo_name: 'SkalskiP/make-sense'
repo_url: 'https://github.com/SkalskiP/make-sense'
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2019 Piotr Skalski

# Customization
extra:
  version: 1.10.0-alpha
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SkalskiP
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/skalskip
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PiotrSkalski92
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/piotr-skalski-36b5b4122/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@piotr.skalski92

# Page tree
nav:
  - Home: index.md
  - Annotations:
      - Import: import.md
      - Export: export.md
  - Integrations:
      - YOLOv5: yolov5.md
  - Changelog: changelog.md

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'img/favicon.png'
  favicon: 'img/favicon.png'
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
    
# Google Analytics
google_analytics:
  - 'UA-155837750-2'
  - 'auto'

# Extensions
markdown_extensions:
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/termynal.css

extra_javascript:
  - javascript/termynal.js
  - javascript/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
